---
# tasks for getting kubectl up and running

- name: Download file from a file path
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

- name: install kubectl
  shell: |
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  become: yes
